qbittorrent:
  hostName: qbittorrent.example.com
  imageTag: "5.2.3"
  torrentingPort: 6881
radarr:
  hostName: radarr.example.com
  imageTag: "6.2.1"
sonarr:
  hostName: sonarr.example.com
  imageTag: "4.0.19"
jellyfin:
  hostName: jellyfin.example.com
  imageTag: "10.11.11"
  transcodeCacheSize: 2Gi
filebrowser:
  hostName: starr.example.com
  imageTag: "v2.63.18"
certIssuer: prod-issuer
mediaSize: 200Gi
proxyUrl: "http://example.com:8080"
noProxy: ".svc.cluster.local,localhost,127.0.0.1"
nodeSelector:
  gpu: intel
additionalVolumes: []
additionalVolumeMounts: []
additionalFileBrowserVolumeMounts: []
