apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  http_proxy: "{{ .Values.proxyUrl }}"
  HTTP_PROXY: "{{ .Values.proxyUrl }}"
  https_proxy: "{{ .Values.proxyUrl }}"
  HTTPS_PROXY: "{{ .Values.proxyUrl }}"
  no_proxy: "{{ .Values.noProxy }}"
  NO_PROXY: "{{ .Values.noProxy }}"
