apiVersion: v1
kind: Secret
metadata:
  name: concierge-chart-registry
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:pTXLWSQ5NR5TGB048t46rXSvrfUMsGGD21UgaFr3vPYHdFEke5rO3TkT4/WfjcRPBLBq+gYQHwde5m0TWKCSrVWk6K/dLkFLGMOkindBeHN9qiQ7Xrp8f2b80+zLRTSRafbTGDw+kPlJFi6Xfn06m/oCCjW1OXBUtbKcpZyO5ineGaYr2DCGGiXjQ1dmR7Bxa4W0g60FnRjx7HZEMnkiwQFp/63G503Ml3+kbpE6qNnCikapYuiIuvmtsfXhHt2nGRjPIMZVA2Llam+OJW/ZDSx41ZzwKVqnXa1hoUbetqqvsiI65zaoVA==,iv:Zm7YFZjz1Onslo3BQv+aj3HM4lpOREfUByjSO4r5NjI=,tag:6CfXbeHfr6Np4AHHOUHPOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN3JSYy9pSXZmcE5SbDlu
        aGJzZGZLU096SG4vWnVnYmh1Q3p4QTNTb1VRCjJpMzNVV0NkNWhuZ1h3N2RORFZt
        NFFLUUNPcmtYcG5PcU1nbG5GZmFlOFkKLS0tICtTRVJyejByQUNuNlVtWDgzS3Rx
        RDNUN1A2K0NwbEp2Y0RBZkdueDNOTm8KRtfxJbHIOFS32mTreGeyDr7m/iiNXS13
        g49AGh1em9CftcLYm5fklycdVREKr0UlVgR58fH5EbkUKmTRiOMvxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T17:40:47Z"
  mac: ENC[AES256_GCM,data:/QpQRLihlETaUzkhK8uBeFDRqVrcyuN8XODvw1DDj4dJj2AYZfTpQECfDZ5+VzAxsnaSr4Uf02CjSngmO8YEpZHyrMFGok14+tXWhtTYmSd5a1+8Z8sNpdLHrXNXb6Lt5E/wxfLbs2LRcLsgOTaNSHsQkuV8a5NE08mxcz2a2JU=,iv:wwbtU9ibYivE0h0mk9tQ2UHixVglkR2nniOAANQqYrE=,tag:Hh+koDL2c5ln5t4sTN9ApQ==,type:str]
  version: 3.13.2
