apiVersion: v1
kind: Secret
metadata:
  name: flux-operator-auth
  namespace: flux-system
type: Opaque
data:
  users: ENC[AES256_GCM,data:QjpCStJBYbkn+yEqgDb/MLWzoLqLG6QjPGtD4PbwWdW8vg0yVleo2+Qbu5YSJKSxjPOUYEah6lFWCSsHyvnEATDeLV+nI2aUJrYNnRXV3dQGYz/3co55zmjBI3o=,iv:IFbC8uvxUTDG99OZTgcX6TYiV2tzxDTx1M7gQTZ45zI=,tag:kNlS85cYfY7ywkEJm95q5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnelU1djZTd0ZTcEd0YVJF
        WkJXRS9uSnFYVUhPUndKWTd3TDFFM0ZJMjI0CnNVQlBvMlM0K1RlK3h3NEY4a2xx
        Nm0zWHF3T1JlbFlrNkNHeVZpUUhscDgKLS0tIG9UN1p2cC9PeFFhVWxOV01wbEZS
        d0tuK1FGMlpRVi9FQjluaTJOcENjQWMKk4+P/HwU7rRfmyOTcHCc6VOHMSHS3sMo
        j02kBFwFVa9BsLkHBxwc0Km+58RA76+G2P52gJ9B7LCI6jaeh1XOlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T19:27:32Z"
  mac: ENC[AES256_GCM,data:M6Kxs206O/RD27f4+T3GFGHlfaHUt3qdLacfu8QZcHYAi/A8yR7wsq/PjaRz+Yje2TtBbX6/QA4vIzSRln27MR3lSSXjf18HJQNW9z4AtDS7dWKIESgJoCLdyjRicA64XyHtMRuSoHkBG8eWtM2rQ2mE5cA73iarVm0wl4gM86k=,iv:s2QYVfsefM+cYtkvEIKOmOGSSmf5bbDX7xQnB4YS+M0=,tag:OKW0LamBJTXsMNtWC5oKpA==,type:str]
  version: 3.13.2
