apiVersion: v1
kind: Secret
metadata:
  name: traefik-extra-auth
  namespace: traefik-extra
type: Opaque
data:
  users: ENC[AES256_GCM,data:ngaQY6UdajPNQgNYY3cXlCOl5nLgI3IOaFnmCD0tHEIFnLSZX93Rm2i0Gc+EHWAJX2tfsnrLdiRRl+Gjn8f1w6GouZwVe5TQc9+94aaVOA3xCYFUfyn/GFNoNKU=,iv:IFbC8uvxUTDG99OZTgcX6TYiV2tzxDTx1M7gQTZ45zI=,tag:vmWe243ezvIvQ/LnTomziw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTE1rQ0t0ZnZFbDRmM0NI
        Z1hwdVBncnNrdjV1eGQ1VEswdkpvdCsrYnpFClVXdGRJbDNxamtGUnlpSnE4Z2pC
        V2g5WGtmUnBtOVV2bWdySE9hZ2djYkkKLS0tIFFKQWtIVEFWbXBxMWw0cnZkaEVZ
        Zk9lWVY3c1Y1ZGNhQldlT0UwanVZUE0K0zV5AM8/kcVhfoZ1lRlwz4XLidW4Iz0W
        SIopyZyBrrIpds3GCJAEvyQGUllQ9YW/pfbViVJBX0+V8XDha4JQDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T12:27:22Z"
  mac: ENC[AES256_GCM,data:1duBhDZar6FFwYgpO/l7TkvC7zQKMtKWDsaXGr9vL22es4jahkRKuOe8WP5OenO2hyYhzlOvkuYwL/q8TZlS6ID5JrIHxHDoxlIeAG6DmP4tFIiMIuPnJP+8WUzw0DVeRBfOFOtk/XCqrxQHSD9x6Vea7krr5q3Z0a1tk56Phig=,iv:dLV2d2lVV838dCrZktlPptw0BUdtAXaMpkBuA7JZ2Fk=,tag:ozTJc4RdU/V3PCNvq99hSw==,type:str]
  version: 3.13.2
