apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: qbittorrent
    - port: 7878
      targetPort: 7878
      name: radarr
    - port: 8989
      targetPort: 8989
      name: sonarr
    - port: 8096
      targetPort: 8096
      name: jellyfin
  selector:
    app: {{ .Release.Name }}