apiVersion: v1
kind: Secret
metadata:
  name: concierge-secrets
  namespace: concierge
type: Opaque
data:
  pakt-token-encryption-key: ENC[AES256_GCM,data:OdVErFwtXZmFtptmVRypEaMHeST5WwslUFVVJbx/E2srodhdS6dJBBNnvvw=,iv:1wsEVNiX62mC7i9c0f5uyA8voKSlS/w0Qjsp3MuC/g0=,tag:Wfp3pd7vr0pF1xp3M+epmQ==,type:str]
  telegram-bot-token: ENC[AES256_GCM,data:dPDmL0fbLcLzTxGQWA0owxitPJbHXUnIHlEUsx6PvAmM6yJSsEH++esmdhsOsYo19b/6Zv+sdI5o2usCi8iVoQ==,iv:ZMaCRLfyExwB0AdStMySU5g35GJ/f1ixsHXqMtSw5zA=,tag:j4nqUuxQ0TqS0YApSK6xFg==,type:str]
  telegram-proxy-url: ENC[AES256_GCM,data:2/myPrRyAkeUprsNcvkUuLV+ZmXUQQXYAe7JNE3/MAFZAXXe/kUshi7hp40I9QNk2VLaBa1xUaTXSXvMsLuzxA==,iv:SYUUcxrDsloPy6/Mk3lwyYw73WSX1evIhDHFouRBZcY=,tag:wmLWJ8irwG2qSfxsWxIFVQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb1hLRUVRYmpRbkpPcURy
        ek9Ra2F5T2V4VjFNaUpWemkrbFhIRDJ5SUg0Ckd4WmxNRnYzL1o0OWY0dkFPOXdX
        Y3dtb1ZSejlMMXMyZU41MXdobXVzZ2sKLS0tIEVSbGFQMjhUeGpZZXhmQnhoZTRO
        b0hUNktaNEV6Q1QvR2F2Q2FnaFozb0UKZe/skLDNOO5sjD8HMP36UgqpvF30whuc
        zagYmfYpYP/QAc0NLUZaYZe1HZl29KUuGTW3GrAu+txF8qkEwcTsSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T12:27:22Z"
  mac: ENC[AES256_GCM,data:6sRrpb86emMAkdmrruZd1LxaQF0OcAYks8uEX5BbNHxCbqKpA5bUPxHHqlS9D9LHzzq2a5vjlK8Hs9adNRKyt+gpY/cXdL8GL87+6xeP4jzZjvbNb4knwj/95wCv16wdEd+QOig489VReaMJcIRz5gn2Y/VY9ViCrwURV5Rdfzc=,iv:7K9jMUd8hVHHziubKV7765QH5S0ecrFcoebqeOx1xv8=,tag:i9GeQfMsJphMvCewh1Pc6A==,type:str]
  version: 3.13.2
