apiVersion: v1
kind: Secret
metadata:
  name: flaresolverr-proxy
  namespace: flaresolverr
type: Opaque
stringData:
  PROXY_URL: ENC[AES256_GCM,data:jEAqSHq22W4QibH8XDx7qaypIcee9AKjUw==,iv:H0lRt7Z1YsH8fmaDG/Nr3olSAsb56/LXlVzw0AIMw20=,tag:ARFUqnDGqUCIUabPovA4nQ==,type:str]
  PROXY_USERNAME: ENC[AES256_GCM,data:OW6vfPTD+15fhw==,iv:OGkhPaT8GDYDjMLFLCagJExcIFDMoN2WgAtNNqXlnIo=,tag:nxHU5eEWJlDUFaQrvVnVJQ==,type:str]
  PROXY_PASSWORD: ENC[AES256_GCM,data:MxEncVpzLYK0Yg==,iv:2lAXDwapk8h3o1D2Psj40WcseHOJutnNEkJsyLT4RMk=,tag:0VnHz8FX9/MC/lfKDLjEZg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOLzRyRDdKRm1FTnBPVmxy
        Nzh2YTZISGR1L09DYzg2VTh5VkxPNStRa0dzCnRhd0huQTdNbWJvUithVTUxS09L
        TGRFRXpsT3U2S0k0WW9KNG0wSkdpQmMKLS0tIHBzdzZ3R1B6dmEweHFFVjJPQU5q
        d3l1U1hzNXBQL0RmTjB2VW5tR2tPL0UK6PMPoblhAruLxRwEAK3wYvdtXYKBqETD
        qD6jtR+GSIa262bLOZ2aocM8M6hk9AokI+Hvbza0bc25WpZfZWB6Og==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T19:15:27Z"
  mac: ENC[AES256_GCM,data:OW3mSd1zX94q/hh+y5TVatptzIir9jrvQ5Pgw/0SrBPGzAs6uSQYGcHVnQwruo2o2CRK5wSD+x2khtbwOWHXifcFjUTnVr8+maKjDxdJWoEoPCzrGWQwc1zPXs+lYyibMwBbqQ9YLlJg9V/kjbq+OT4689Wdz6aU6u3DqoU8kLY=,iv:5+WXzDXxD95sQpJBMWLEShqc0NDnDdwLoMUBRm/xMSk=,tag:8a8lsytEJxY4GXBKCsNY2w==,type:str]
  version: 3.13.2
