apiVersion: v1
kind: Secret
metadata:
  name: ghcr
  namespace: concierge
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:oW8E8j9ztyPIjM0xqBzKJWmshYJpa/N0x8MC71fjE9CxsTa73/4vABJdVaAS0p9Ajexn4WrKJjOG0aexlFWRH447XjViN2fdwFlbX6Xwl0okVG0H2S2M/904903NFN/zXE3jm6gtJJGYmWpHsKIrrDvSPYf3esiCVpKWfb+fbLtE+yOKj+fH9ZKjMYDEYS6IpjPyiGZybXQ10WKUTnKYRqQQi9/pfEyBLBWj0lORDs4+byFijiHhfrGsabTlFnWeqOr1t3lA9atJ/cilqA3vUBZOyqvbNRSt1542quZ79F4eFBsJPKh+Ng==,iv:J1JETSnqgaVkrsrrQsTvx1DR0FH0ApT9c4MsI4wAGOo=,tag:IxxnSebeDJ0VTy/XNvl4RQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUXFuMkdFeHc5cjBpMWtW
        Z1NrR2tMK3NKcExWWGloNkI1Qm5SaCtCdFY0CkhrTy90dHcyMy9hTVYxS2t1a3hB
        Nk9iNndQS3EvVXRlVXhibHYzWDhIQXcKLS0tIFp3WlU5ZksrL2ROY1dTdUV1QnVS
        REhKem9udWFNczJHR0pSNjNPWGkyY2sKmqCq3wVCQ1/e1J8rdisp5OSYDAJr2laN
        VOvdpxmbma+f8axTn1SApo8DV1TDdAnjSu2g38AWh0q5ebzDOFz9Pw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T12:27:22Z"
  mac: ENC[AES256_GCM,data:n0g0P1mHIol/V6qOOxSqqOsPl+UTAe3Ks43O0bU7ih92ZPUxhWxBeXDgyxgIotvWwUpi40/YrwCmdd+bvSeQGPYLZBOZC0nbvGV4Uq/ew6E0zQpzmvUjyZ0J4uGCYuAtF41jAbtbGj9p0jqvoloa9IhK0/KVqbVbAv8VGhjYHag=,iv:5BRp8A3putcD+Chv2XCUq4FBT6z8cQ7iIHOEaF2psbk=,tag:7tPnzmJPPXVoU0/y+72rqA==,type:str]
  version: 3.13.2
