apiVersion: v1
kind: Secret
metadata:
  name: gluetun-credentials
  namespace: gluetun
type: Opaque
data:
  password: ENC[AES256_GCM,data:tK8A8dvyhKVDm+eaIFF1bw==,iv:cIrJ1BuVtz8Zp0ay7iijTm3ow1CBwb3E+gGAG/5Jk28=,tag:IRP59ne9fx5M7Rm/dnjlrQ==,type:str]
  privateKey: ENC[AES256_GCM,data:PHqofANoJdakiNtd+IX3IkUz1ECE3OVvISt4LyUww/B7rJ8KFZPCAGVBDZ6A9TGSqd8tQoq4Cs8oPNIN,iv:x1WVM82ESoeOSPdyy3sTpBePDLw/SCF5ccVMJMFpqtU=,tag:MpE3m1t2O/haYCzrPz4jtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcTAzRHo4NmQzR0hManJI
        eVpJd1h1M1RSN2E5MjYrYVcwRmJtU2NnZkVFCjRuRDJYU1FpMnNUbCt4M3VDN0pa
        VUk0TVZaMVVBcGV2UkxWekZYekdsL0EKLS0tIGh2R0pGN0ZoeFdCYlN5eGpYc28v
        a2JlN2crME40T2NuYTl4R1RlTmFudEEKikBm7dXi7/kzGatY50vK3jkWTm5IAUmx
        jQEdeBr4wrjc5VS0OkUiAYOTv7k++R815UUxRvZm4KqD173zCiOZaQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T12:27:22Z"
  mac: ENC[AES256_GCM,data:PbHxPvXfg2AFiv1YJoOCf2kmTdHwcz4hQL68PtXtV7yKx2g38tUq35YyWGydpwbgP/lQgx+o1k7UtM+PNdh59585KhMafT10krFnIuK/bT06sX7CylcFY/zfUepf2g7kME8cp6FBTpqfILQWx8vB4jfclH/xUDK5D1WFsnctaAQ=,iv:32NrM2yu0lkbk8nWr1Bp2gCQ0n9rrLuAwD+BaYNDxa8=,tag:OxEaQFqax00nwlQvABV/9g==,type:str]
  version: 3.13.2
