apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-api-keys
  namespace: recyclarr
type: Opaque
stringData:
  radarr_api_key: ENC[AES256_GCM,data:A8H22mBNlEnw4EwWkB7t1FoaDU65IfylfJgOkKoX9jc=,iv:DWBPyjoxzYfMcWBwXI1Y6tAxs2ryzpPNFTMtAjh/DmI=,tag:T79Q9bUTBWFMR0poS1v3vA==,type:str]
  sonarr_api_key: ENC[AES256_GCM,data:YzQN8J9BrhnLluj+BF0KfQ/HL2f5PMKvPbPsrejfiwQ=,iv:qrUM6RxNpz2c6TzQwWBP/hwV1+0DcBoEEd0BU7ldDkI=,tag:ZB/3rGPjT7dt6E7/AsOXQg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTkJhYkdWbzhkTzd6VElw
        YmJ2TXBUR3F0Ym1NVDZQTVRldWU5M0hwZDFVCnZ1eXp3SHZ3dmdIYjNyZTV2ekZM
        T3BGMXAwcVVFRFVjbmlpRm5CYTZFYm8KLS0tIFQ1Sll6ZjAzUG11b3RFUnBDTTRK
        WlpQbW80UmlmSUJZYSt5SmhxeEpjYkkK9Psvueeh2zlPFVuaZZidM1uHeI9q2/7w
        HPwYQit9Xs6dKmglyJD2CKz2geC+NcNZD6dSviwZiPlnzhcLUfoLUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T12:27:23Z"
  mac: ENC[AES256_GCM,data:NjrrKvdAT153Ow/ZBwbFOoZKIBteGLksyGitC9TQ84JG5p4QkqJMmu20qUBVBFloMgT2tlW4o1knzZ82gd0L+/MEgYdM5trkla4bPKeCNS8EL9AwXO/qayPfXJmZf+spvVskIPRQKVTFk1HMZYI3cZJzvGWdXQOOaCFkzwR5VFw=,iv:saxjGDs3R/7UKLb1K68Gq6ibB5Ogo9o8rO/R71OhMZA=,tag:WIwa/QOEUIF2xj9VkpjfwA==,type:str]
  version: 3.13.2
