apiVersion: v1
kind: Secret
metadata:
  name: torrserver-earth-credentials
  namespace: torrserver-earth
type: Opaque
data:
  accs.db: ENC[AES256_GCM,data:ig2h54ky9IprwEYVKuA7JlBFfwEqCKNHwyg1CWYcm/m1AAWqiCYWVA==,iv:RNQTbzKlijwPdKgChJIaF31DAtsAo++xARKAiBcE8pA=,tag:8wW6hCmF0LZ+lDKKbkTb9Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YXVzNE56Qlhwc2hmSDVQ
        MktHNnNrbjBPTkIxNXN5TjdBQ21DbXYzNTNZCmVkYWRzT1Fvc2pXNUMrMmtRNklF
        eTZiM0pQeVVqeG5WUnJlTUhBQU13b3cKLS0tIEdEczJobVFlaVpwbzRUYjJxTXVN
        UnBqU1lnY0VsU0RVUlVhQUlEMS9OTHMKkNUe5CxmNOJnAbkrbzqQXpxs2HP8KnHm
        PFBcqWf6zGdZQfFHd+vQFRWRko3UrFSPwnHsP0elAkCpz3qH8b07fg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T12:30:18Z"
  mac: ENC[AES256_GCM,data:sFzFkqYiJM7qb/W306bRGLN3H8X9GSj7qxgMfoLKuBieU+Fk9f4/xncgMRCrr5axeKsLsaRcX4CqnWJJlhQRAem2mP0Qr1AhRAQbGi8jEPsYRSCZOokS7fGAxq5s8U7qCTR0zTw6ti/Vu58yeXoMRxhom2tPa306FrgJfxecTe8=,iv:/vjDgP503l0Er9Frq6lpOc8q03qSFfmyO7j2HmPpSaI=,tag:Kqtr8PjcH+LQQxhUiPK/fw==,type:str]
  version: 3.13.2
