apiVersion: v1
kind: Secret
metadata:
  name: torrserver-moon-credentials
  namespace: torrserver-moon
type: Opaque
data:
  accs.db: ENC[AES256_GCM,data:xs2InZ7I5jpI5Ae8TZ9lN6oDwtD7UtUzx50Ydthtqt/8HIrKqdCBXw==,iv:KB8oQ2aqYdOQwtf3jIoP/X7nRH9vBtPbPjpLgMjGXCU=,tag:yCqiEWxtee27Y6bMyICu3g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN3lRbGovR3Z3ZlpUYThT
        WUVBeHJaaHFvbmJ4dHdyODdySnY2QkpsZFZNCndLaFo5UEFkbUNxdEN0VktVSFdX
        U2lKMi9lZFdnM3JuMXAyUHcyN1NaemsKLS0tIGMyM2FDUGkveDIvT2dqSTc0MU5n
        dGdpWFQ0RmJGaVNZS1dmWjg5cEJua28KRYX4qANZSZYR6Rt97wanB5ec6GuSd4rV
        pRgPGjGlexVGIUDYtS1kyGzKQyvlV30cgpMbq9vtjV6xH3aBYhTC2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T12:30:18Z"
  mac: ENC[AES256_GCM,data:LkMz1k6JP0zxF6/0jkExnzV51O3aNqTT9P63ioGHn7Y4NjIsNLlRmfUOvsSkXmkCnQYR59l2U7lR3dc4a9do2cG26rhrYXTNqcDlzjsXCbjJWKy+y1u0hqpkrORDOUGKVCQdhrsJt3BooXCzRz7OuzaaOZR9f2nJ4Anh2wKY6jg=,iv:zLGJEA+JtBYLNJl+RotgXwg2VEuEe749kM20qXceQ/8=,tag:Jos1bWMOriq365SiCUfcMQ==,type:str]
  version: 3.13.2
