apiVersion: v1
kind: Secret
metadata:
  name: wg-easy-credentials
  namespace: wg-easy
type: Opaque
data:
  password: ENC[AES256_GCM,data:+YAkI3RuWaAO1zXEpaOWxHL0p8nCymvxoDwOr4d74rJLxoZjE2eSAO2+kdZz+hj2az7Jd7PHvQKlR8PRwXRFkyfC+n9NloZF8uh1Pgd9ufA=,iv:Dv6YX5fz8S2YwEcdSf0YGxnFfQTrw73JLSxeeoJd2kc=,tag:IkdcJmMP00KDOthXprAiAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV0tTMmFCdWpHOFVRTWp4
        bFIrVUllKzJLYTE0b3dheCt2Z240RGc1Z1hjCm05Qk1OZVkwTG5kWE9NbmdOa1A2
        bUVSaVBrSE5kWFdMeXB5Qk9xODRKUk0KLS0tIExWeWRCd2d3c3k0M3N6L2VCaEtF
        Q0xMRlE0VjRzQmg2Y0RIT0I0dmNBVjAKM9kKRzUymsWtWl8Re4owuIWZOSA1O2go
        YNP4tQ6UnNA+0VqUa34+pa14EfPG88qljznMGja2sgHcSKOGDDPlgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15vtwlajesqw3xh08jzqajfkrtuusgzptq6vjywxdthynk3ss036ql6mlmh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T12:30:18Z"
  mac: ENC[AES256_GCM,data:+0RHKSU3MAXdkkQtBkEqdJINOWZ0AQ/d/h1Sc3w10lXj8EBFL9HXh1UhE6p5DLYTNJQ3mP3PxZhHnCdPuwiJbViDiEr1iThzmuJsibCOcCMtk1qoFtG6EWxOqe0h7MyKWwJKZRx4I1Sw6UuD70FAh3tQpv1FTdh2tBQl/ez1Ey4=,iv:Zr12PsPI1UTexB9Oqiug9YN+dCfxVteM2/wa1n5tbh4=,tag:vHAD5IOSQk/SXW0YI/t2Ew==,type:str]
  version: 3.13.2
