apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 56335
      targetPort: 56335
      protocol: UDP
      name: udp
    - port: 56335
      targetPort: 56335
      protocol: TCP
      name: tcp
  selector:
    app: {{ .Release.Name }}