apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: {{ .Values.incomingConnectionsPort }}
      targetPort: 56335
      protocol: UDP
      name: udp
    - port: {{ .Values.incomingConnectionsPort }}
      targetPort: 56335
      protocol: TCP
      name: tcp
  selector:
    app: {{ .Release.Name }}