# Existing Secret must contain an accs.db key with TorrServer credentials JSON.
existingSecret: ""
hostName: torrserver.example.com
certIssuer: prod-issuer
incomingConnectionsPort: 56335
nodeSelector: {}
