apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 51820
      targetPort: 51820
      protocol: UDP
  selector:
    app: {{ .Release.Name }}