apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 51821
      targetPort: 51821
      protocol: TCP
      name: web-ui
    - port: 51820
      targetPort: 51820
      protocol: UDP
      name: vpn
  selector:
    app: {{ .Release.Name }}