apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: flaresolverr
          image: "flaresolverr/flaresolverr:{{ .Chart.AppVersion }}"
          envFrom:
            - secretRef:
                name: {{ required "existingSecret is required" .Values.existingSecret | quote }}
          ports:
            - containerPort: 8191
              protocol: TCP
