apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - flaresolverr.yaml
  - gluetun.yaml
  - jackett.yaml
  - starr.yaml
  - seerr.yaml
  - recyclarr.yaml
  - torrserver-earth.yaml
  - torrserver-moon.yaml
  - wg-easy.yaml
  - concierge.yaml
  - secrets/concierge-secrets.sops.yaml
  - secrets/ghcr.sops.yaml
  - secrets/gluetun-credentials.sops.yaml
  - secrets/recyclarr-api-keys.sops.yaml
  - secrets/torrserver-earth-credentials.sops.yaml
  - secrets/torrserver-moon-credentials.sops.yaml
  - secrets/wg-easy-credentials.sops.yaml
patches:
  - target:
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/maxHistory
        value: 10
