apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: starr
  namespace: starr
spec:
  dependsOn:
    - name: clusterissuer
      namespace: default
    - name: longhorn
      namespace: longhorn-system
    - name: gluetun
      namespace: gluetun
    - name: jackett
      namespace: jackett
  interval: 30m
  releaseName: starr
  targetNamespace: starr
  storageNamespace: starr
  chart:
    spec:
      chart: ./charts/starr
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    qbittorrent:
      hostName: qbittorrent.nishiol.ru
      imageTag: "5.2.2"
      torrentingPort: 6881
    radarr:
      hostName: radarr.nishiol.ru
      imageTag: "6.2.1"
    sonarr:
      hostName: sonarr.nishiol.ru
      imageTag: "4.0.17"
    jellyfin:
      hostName: jellyfin.nishiol.ru
      imageTag: "10.11.11"
      transcodeCacheSize: 2Gi
    filebrowser:
      hostName: starr.nishiol.ru
      imageTag: v2.63.15
    certIssuer: prod-issuer
    mediaSize: 300Gi
    proxyUrl: http://gluetun.gluetun:8080
    noProxy: .svc.cluster.local,localhost,127.0.0.1
    nodeSelector:
      cpu: medium
    additionalVolumes:
      - name: media-raspberrypi4
        persistentVolumeClaim:
          claimName: media-raspberrypi4
    additionalVolumeMounts:
      - name: media-raspberrypi4
        mountPath: /media-raspberrypi4
    additionalFileBrowserVolumeMounts:
      - name: media-raspberrypi4
        mountPath: /srv/media-raspberrypi4
