apiVersion: networking.k8s.io/v1
kind: Ingress
{{- $hosts := list .Values.hostName }}
{{- with .Values.legacyHostName }}
{{- $hosts = append $hosts . }}
{{- end }}
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certIssuer }}
spec:
  rules:
    {{- range $hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: 5055
    {{- end }}
  tls:
    - hosts:
        {{- range $hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .Release.Name }}
